name: Run Unit Tests
on: [push]

jobs:
  Run-Pytests-Linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}/cvm-attestation
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e . -v
      - name: Run Pytest
        run: |
          cd ${{ github.workspace }}/cvm-attestation
          pytest --maxfail=5 --disable-warnings

  Run-Pytests-Windows:
    runs-on: windows-2022
    steps:
      - name: Check out repository code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: '3.x'
      - name: Install dependencies
        shell: pwsh
        run: |
          cd ${{ github.workspace }}\cvm-attestation
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e . -v
      - name: Run Pytest
        shell: pwsh
        run: |
          cd ${{ github.workspace }}\cvm-attestation
          pytest --maxfail=5 --disable-warnings